language: php
addons:
  code_climate:
    repo_token: 90bbb69b0bc978faa2d9fe608671907c94def03742eaae1328e8f5b6b790be2d
before_script:
  - composer self-update
  - composer install
after_script:
  - vendor/bin/test-reporter
